### ISSUE TITLE
The verify command should have the option to write a log file

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/command-line-interface#31]
It may be useful to have the output of the behave steps logged to a file for
future examination.

**Comment by pbelmann** [comment]
@michaelbarton  are you already working on this?
If you do not, I would give this issue a try. (You can assign this issue to me)

**Comment by michaelbarton** [comment]
Yes, that would be helpful, thank you.

**Comment by pbelmann** [comment]
It seems that PR #58 does not solve this issue. Michael could you explain the purpose of this issue, please.

**Comment by michaelbarton** [comment]
Sorry for the confusion Peter, my original description wasn't clear enough. I
looked at your implementation and as I understand it, this writes the output
that would be written to the STDOUT and instead writes it to a file. What I had
in mind was instead to write the behave output to a log file.

For example when a verification tests fails, the output rather unhelpfully
reports 'FAIL'. I had in mind that a log file could contain the behave output
written to it. This could then be inspected by the developer for the reason
why, which would would make debugging failing tests easier.

The behave JSON output is collected in this command:

``` python
results = behave.run(biobox, image, task, False)
```

This is however JSON output, because this is what is parsed in the subsequent
steps in `biobox_cli/command/verify.py` to identify the failing scenario names.
Possible options for a verification log file are:
- Write the JSON output to the log file. This is sort-of human readable and
  probably better than nothing.
- Parse the JSON output back into human readable text. Might be a little
  tricky as the behave output is not exactly simple.
- Run the behave tests twice to collect human-readable and JSON output. I
  don't really like the idea of this though because this doubles the running
  time of the verification.

What do you think?

**Comment by pbelmann** [comment]
I see. I will take a look at it and prepare a PR
