### ISSUE TITLE
Remove containers

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/command-line-interface#40]
CLI should remove already executed containers after a successful run.

**Comment by michaelbarton** [comment]
I agree, however I have encountered problems on circleci using the `--rm` flag.
I don't believe the circleci file system allows the removal of containers. A
possible work around would be an additional flag `--no-rm-container` that could
be used in the feature tests on circleci.

**Comment by pbelmann** [comment]
ok

**Comment by michaelbarton** [comment]
Thanks for implementing this. I merged your commits in. After looking at the
interface, I think my suggestion of `--no-rm-container` could be a little
verbose. It could possibly be changed to `--no-rm` for brevity. This would also
match the docker client flag `--rm` too. What do you think?

**Comment by pbelmann** [comment]
:+1:  I agree  see PR #49
