### ISSUE TITLE
Refactor Run Modules

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/command-line-interface#52]
This issue is for DRYing code out in the run modules (at the moment: short read assembler and assembler benchmark).

I recommend using python abstract classes for providing general functionality like:

A base class with :
- abstract copy files
- abstract get_mount_files
- abstract get_file_arguments
- run command with the following functionality:   
  - exit if no image available
  - run the container
  - remove the container
  - parse biobox.yaml
  - call the implemented abstract methods

This would allow to encapsulate repeating code snippets of the run command in short_read_assembler.py and assembler_benchmark.py and ensure that the run modules implement all necessary methods. 

At the moment I do not know if this will work with docopt but if there are no objections against this approach, I would give this a try and provide a PR with an example implementation.

**Comment by michaelbarton** [comment]
Thanks Peter I think refactoring this will be a good idea since we'll be duplicating the same code.
