### ISSUE TITLE
Make command line interface python 2/3 compatible

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/command-line-interface#71]
In PR #67 @luizirber has made the command line interface python 2/3 compatible.
This however still fails a feature test for the `biobox login` command.

I've spent some time today debugging this and trying to get the login feature
to work. I still haven't resolved it. Something appears to be causing the login
command to create a broken pipe when I try running the command manually. I'm
not sure why this is happening as this @luizirber's original PR did not touch
the login code as far as I can tell.

This login code should be fixed before we merge the
`feature/python-3-compatible` branch into a new release branch. Anyone is
welcome to try and resolve this, otherwise I will continue to look into this
myself.
# Please explain the issue. The first line will become the title. Trailing
# lines starting with '#' (like these) will be ignored, and empty messages will
# not be submitted. Issues are formatted with GitHub Flavored Markdown (GFM):
# 
# http://github.github.com/github-flavored-markdown
# 
# On bioboxes/rfc

**Comment by pbelmann** [comment]
Any progress on this issue?

When I bootstrap the "feature/python-3-compatible" branch with virtualenv set to python3 ("--python=python3") even the "--help" feature test fails.

**Comment by michaelbarton** [comment]
I haven't had time to look at it recently. Do you know what is causing the
errors?

I was having problems with the `login` fuctionality on the python2 branch
which was I wasn't able to get working.

**Comment by pbelmann** [comment]
python 2 tests are fixed in #72  . python 3 tests still do not pass
