### ISSUE TITLE
The '0.4.0' release is currently broken and cannot be merged into master

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/command-line-interface#87]
The reasons for this appear to be:
- An error when trying to create Docker containers. The error description is
  `AttributeError: 'AutoVersionClient' object has no attribute
  'create_host_config'`
- The "bioboxes/quast" image is not a valid biobox. This appears to be due to
  the `COMBINED_OUTPUT` variable not being found in the `run` script.

**Comment by michaelbarton** [comment]
PR #86 fixes the `AttributeError` when trying to create a container.

**Comment by michaelbarton** [comment]
PR bioboxes/quast#4 fixes the quast biobox so that it passes the verification tests in the command line interface.

**Comment by michaelbarton** [comment]
The version 0.4.0 branch is successful working in [CI build 271](https://circleci.com/gh/bioboxes/command-line-interface/271)

**Comment by michaelbarton** [comment]
@pbelmann Would you mind if I merged this release into master?

**Comment by pbelmann** [comment]
I think you can merge it. Thanks for fixing the issues.

**Comment by michaelbarton** [comment]
Thanks Peter

**Comment by michaelbarton** [comment]
Fixed
